### ISSUE TITLE
Conda package maintainers needed for Windows (and maybe OSX)

### ISSUE THREAD

**Issue by hanslovsky** [hanslovsky/imglib2-imglyb#6]
See http://forum.imagej.net/t/imglyb-and-pyjnius-conda-package-maintainers-needed-for-windows-and-osx/11420

**Comment by jakirkham** [comment]
If you are open to adding them to [conda-forge]( https://conda-forge.org/ ), there would be a vibrant community with people knowledgeable about building things for various platforms (including Windows), who you could ask for help with this sort of thing. Plus infrastructure designed to aid the build and deply process. Does this sound interesting?

**Comment by hanslovsky** [comment]
Sounds good to me, I will look into that.

**Comment by jakirkham** [comment]
Happy to help out. We have done a fair bit of contributions to that org.

**Comment by hanslovsky** [comment]
Maybe we can get together sometime this week. Are you free this afternoon?

**Comment by jakirkham** [comment]
Have a meeting this afternoon. Would Thursday or Friday work for you?

**Comment by hanslovsky** [comment]
Let's do Thursday at 1pm. Does that work for you?

**Comment by jakirkham** [comment]
Sounds good. Meet in Bob's?

**Comment by hanslovsky** [comment]
Bob's works.
Collections some relevant links:
- Java build requirements
   - https://anaconda.org/anaconda/openjdk
   - https://anaconda.org/conda-forge/openjdk
   - https://anaconda.org/anaconda/ant
   - https://anaconda.org/anaconda/maven
   - https://anaconda.org/conda-forge/maven

As you can see, some of the packages are available on anaconda as well as on conda-forge.

**Comment by hanslovsky** [comment]
[imglyb](https://github.com/hanslovsky/imglyb) is distributed as [`noarch` package](https://anaconda.org/hanslovsky/imglyb) and uses `jrun` to resolve jar dependencies. This can be closed now.
