### ISSUE TITLE
Separate imglib2-imglyb and imglyb (python)

### ISSUE THREAD

**Issue by hanslovsky** [hanslovsky/imglib2-imglyb#7]
This separation already happened in 703dcec
Things to do now:
 - [x] Create separate [imglyb repository](https://github.com/hanslovsky/imglyb)
 - [x] Release imglib2-imglyb to https://github.com/saalfeldlab/maven
 - [x] Re-write imglyb to use python jrun bindings instead of fat jar
 - [x] Create imglyb conda package

**Comment by hanslovsky** [comment]
Closes #5

**Comment by hanslovsky** [comment]
Finished all to-dos in initial comment

**Comment by imagejan** [comment]
@hanslovsky wrote:
> Release imglib2-imglyb to https://github.com/saalfeldlab/maven

How about _also_ deploying to https://maven.imagej.net? That would make these artifact a bit more accessible from ImageJ-related projects, as they use this as their default maven repository.

**Comment by hanslovsky** [comment]
I do not plan to do that personally but I am not opposed to that, contributions and PRs welcome

Adding the saalfeldlab maven repo is easy:
```xml
<repositories>
    <repository>
        <id>saalfeld-lab-maven-repo</id>
        <url>https://saalfeldlab.github.io/maven</url>
    </repository>
</repositories>
```
